Relative Compile Paths
kevboh/longform pull request #187
Opened 2023-08-17 15:10 UTC by b-camphart

Introduces a new function for resolving relative file paths during compilation.  Checks for many possible paths that could start with a dot.  Some of which can be handled, some can't.  Also, allows valid file paths to be compiled, but gives a warning if obsidian won't be able to open them.

fix #149

2023-08-17 15:11 UTC, b-camphart commented
[26fad01](https://github.com/kevboh/longform/pull/187/commits/26fad0121ea0f6320d60bef0f4898a01dfe841b0) shouldn't be included in this PR if/when #186 is merged.

2023-08-17 19:46 UTC, b-camphart commented
Should fix #149

2023-08-30 19:32 UTC, b-camphart commented
@kevboh 
> @b-camphart can you rebase onto `main` to remove the extraneous commit?

Done! 🙂

2023-08-31 19:38 UTC, kevboh requested changes

2023-08-31 19:38 UTC, kevboh commented on src/compile/steps/write-to-note.ts
> +  if (! relativeFilePath.startsWith(".")) {
```suggestion
  if (!relativeFilePath.startsWith(".")) {
```

2023-08-31 19:38 UTC, kevboh commented on src/compile/steps/write-to-note.ts
> +  Possible paths:
Thank you for this list!

2023-08-31 19:38 UTC, kevboh commented on src/compile/steps/write-to-note.ts
> +    new Notice("Obsidian cannot open files that begin with a dot.  Consider a different name.");
```suggestion
    new Notice("Obsidian cannot open files that begin with a dot. Consider a different name.");
```

2023-08-31 19:38 UTC, kevboh commented on src/compile/steps/write-to-note.ts
> +  } while (filePathComponents.length > 1)
This is a very difficult block of code to reason about. I would probably reach for recursion here, but if you're not comfortable doing that could you annotate each meaningful line with a comment explaining what's going on?

2023-08-31 19:38 UTC, kevboh commented on src/compile/steps/write-to-note.ts
> +
```suggestion
  return normalizePath(projectPathComponents.concat(filePathComponents).join("/"));
```

2023-08-31 19:38 UTC, kevboh commented on src/compile/steps/write-to-note.ts
> +
(removing newlines)

2023-08-31 19:38 UTC, kevboh commented on src/compile/steps/write-to-note.ts
> +      console.log('Writing to:', filePath);
I've tried to namespace all logged text with `[Longform]`:

```suggestion
      console.log('[Longform] Writing to:', filePath);
```

2023-08-31 19:38 UTC, kevboh commented on src/compile/steps/write-to-note.ts
> +        console.log('Attempting to open:', filePath);
```suggestion
        console.log('[Longform] Attempting to open:', filePath);
```

2023-08-31 19:38 UTC, kevboh commented on src/compile/steps/write-to-note.ts
> +            console.error(err);
```suggestion
            console.error('[Longform] Could not open', filePath, err);
```

2023-08-31 19:47 UTC, b-camphart commented on src/compile/steps/write-to-note.ts
> +      console.log('Writing to:', filePath);
Good to know!  I'll keep that in mind for future logging stuff 🙂

2023-08-31 19:52 UTC, b-camphart commented on src/compile/steps/write-to-note.ts
> +
I don't seem to be able to commit this change, but I'll remove them in the updated code.

2023-09-04 17:19 UTC, b-camphart commented on src/compile/steps/write-to-note.ts
> +  } while (filePathComponents.length > 1)
Modified into a recursive function :)

2023-09-07 19:28 UTC, kevboh reviewed
Much more readable! A few nits.

2023-09-07 19:28 UTC, kevboh commented on src/compile/steps/write-to-note.ts
> +      if (! atStartOfFilePath) {
```suggestion
      if (!atStartOfFilePath) {
```

2023-09-07 19:28 UTC, kevboh commented on src/compile/steps/write-to-note.ts
> +        new Notice("Obsidian cannot open files that begin with a dot. Consider a different name.");
Thoughts on defaulting to something like `Compiled Manuscript.md` in this and saying such in the notice?

2023-09-07 19:28 UTC, kevboh commented on src/compile/steps/write-to-note.ts
> +      // assume there are no more ".." in the rest of the filePathComponents
Hmmm, this is a big assumption. One way around this is to use the third argument of this function as an accumulator (and treat the empty string as `atStartOfFilePath`), or we just loop through here and error if we see another `..`. Fine either way.

2023-09-07 19:28 UTC, kevboh commented on src/compile/steps/write-to-note.ts
Can you end this file with a newline? You can configure vscode to do this (and even save that config to this project, if you'd like).

2023-09-07 22:41 UTC, b-camphart commented on src/compile/steps/write-to-note.ts
> +        new Notice("Obsidian cannot open files that begin with a dot. Consider a different name.");
I just wonder how much responsibility the plugin should take on.  Having a file start with a dot isn't illegal, we can happily create, and write to, those files.  The issue comes from Obsidian not then being able to open it.  What if someone _intentionally_ started it with a dot?  Should we prevent them from creating the file they want, simply because Obsidian can't open it?  Plus, what if, later, Obsidian decides to support reading those files?  Or adds a setting to opt into reading them?  At least, with a warning like this, we're somewhat unified with Obsidian, but we won't prevent users from doing what they want (and we aren't blocking a potential future Obsidian feature).

2023-09-07 22:44 UTC, b-camphart commented on src/compile/steps/write-to-note.ts
> +      // assume there are no more ".." in the rest of the filePathComponents
My reasoning around this was similar to the above: how much responsibility should we take on?  The comment isn't intended to say "we know there aren't any more `..` in the file path" but instead, "we're going to pretend like there aren't from here."  We could loop through the rest to see if there are more, then issue a warning about it, but I don't think we should prevent technically legal paths from being used.

2023-09-08 13:37 UTC, kevboh commented on src/compile/steps/write-to-note.ts
> +        new Notice("Obsidian cannot open files that begin with a dot. Consider a different name.");
Good points. Ignore me here.

2023-09-08 13:38 UTC, kevboh commented on src/compile/steps/write-to-note.ts
> +      // assume there are no more ".." in the rest of the filePathComponents
My reading was that a path like `folder/../folder/../folder/file.md` would break. Is that not true?

2023-09-08 15:50 UTC, b-camphart commented on src/compile/steps/write-to-note.ts
> +      // assume there are no more ".." in the rest of the filePathComponents
From my testing, my filesystem (Windows) happily created folders called ".." when I put a filepath like that in.  Now, that may not always be the case, based on the OS, but I figured, it would fail when we tried to create the file/folders anyway, if the OS didn't like it.

2023-09-08 15:51 UTC, b-camphart commented on src/compile/steps/write-to-note.ts
I _think_ I got my linter working in vscode now, so hopefully this won't be an issue again :)

2023-09-24 14:11 UTC, kevboh commented on src/compile/steps/write-to-note.ts
> +      // assume there are no more ".." in the rest of the filePathComponents
Fair enough.

2023-09-24 14:12 UTC, kevboh approved these changes

2023-09-24 14:12 UTC, merged