WIP Add GUI for ignoring scenes
kevboh/longform pull request #209
Opened 2023-10-31 18:18 UTC by b-camphart

Moves the code for adding/ignoring scenes into a shared file (to avoid import cycles).  I considered using the context API, but it erases all the typing and, since all the logic used shared stores anyway, I figured this design couldn't hurt.

WIP because we may want to add a GUI for including scenes back into the project, but I'll wait to hear from you @kevboh :)

2023-10-31 18:22 UTC, b-camphart commented
This should fix #173

2023-11-13 18:38 UTC, kevboh requested changes

2023-11-13 18:38 UTC, kevboh commented on src/view/explorer/UseCases.ts
Could you rename this to follow existing file naming conventions? I would instead call this something like `scene-menu-items.ts`

2023-11-13 18:38 UTC, kevboh commented on src/view/explorer/ExplorerPane.ts
> +          item.setTitle("Ignore scene");
Technically the file is not meant to be a scene, so I would instead call this

```suggestion
          item.setTitle("Ignore note in Longform");
```

2023-11-13 18:38 UTC, kevboh commented on src/view/explorer/ExplorerPane.ts
> +          item.setIcon("document");
```suggestion
          item.setIcon("minus-circle");
```

maybe?

2023-11-13 18:38 UTC, kevboh commented on src/view/explorer/ExplorerPane.ts
> +          item.onClick(() => ignoreScene(file.name.split(".")[0]));
This breaks for files with multiple periods in the name—also non-markdown files won't appear here, so we can safely trim `.md` and use that instead.

2023-11-13 18:38 UTC, kevboh commented on src/view/explorer/SceneList.svelte
Please update this file to not include formatting changes—can't review like this

2023-11-13 18:38 UTC, kevboh commented on src/view/explorer/UseCases.ts
> +}
files should always include final newlines

2023-11-13 18:38 UTC, kevboh commented on src/view/explorer/ExplorerPane.ts
> +}
Restore newline

2023-11-20 18:43 UTC, b-camphart commented
The formatting thing was a nightmare 😅  But I think I resolved all the changes you asked for.  The question is, do you want to have me include a GUI for re-adding notes to the project?  Would probably require some new GUI design to do it.

2023-12-11 12:03 UTC, kevboh approved these changes

2023-12-11 12:04 UTC, kevboh commented
@b-camphart no, this is fine.

2023-12-11 12:05 UTC, merged