Prevent null selectedDraft from breaking render
kevboh/longform pull request #219
Opened 2023-11-20 21:01 UTC by b-camphart

fixes #218

2023-12-11 16:46 UTC, kevboh requested changes
See suggestions—I want to make sure undefined indices are handled and can be read cleanly. Thanks for the PR!

2023-12-11 16:46 UTC, kevboh commented on src/view/compile/CompileView.svelte
> +          $selectedDraft &&
Is this not already checked twice above? Is this needed?

2023-12-11 16:46 UTC, kevboh commented on src/view/explorer/SceneList.svelte
> +      $drafts.findIndex((d) => d.vaultPath === $selectedDraft.vaultPath);
I think this would be more readable (and not make people reason about an undefined `currentDraftIndex` as

```suggestion
    if (!$selectedDraft) {
        return
    }
    const currentDraftIndex = $drafts.findIndex((d) => d.vaultPath === $selectedDraft.vaultPath);
```

2023-12-11 16:46 UTC, kevboh commented on src/view/explorer/SceneList.svelte
>    }
What does an undefined `currentDraftIndex` mean? Is it handled throughout? I believe this whole block could also be written as

```
$: if ($selectedDraft) {
    currentDraftIndex = $drafts.findIndex(
      (d) => d.vaultPath === $selectedDraft.vaultPath
    );
}
```

2023-12-11 16:46 UTC, kevboh commented on src/view/explorer/SceneList.svelte
> +    const currentDraftIndex =
Same suggestion as above

2023-12-11 21:18 UTC, b-camphart commented
@kevboh applied suggestions!  Also, I found another bug related to this in which steps in a workflow were sometimes `undefined`, causing the same issue of the panel being unresponsive.  I removed a binding in a svelte component, which I didn't think was necessary, since the component never actually updated it.  Seems to have fixed that problem, and the fix doesn't seem to have changed any functionality.

2024-01-03 03:08 UTC, kevboh requested changes
Nearly there.

2024-01-03 03:08 UTC, kevboh commented on src/view/explorer/scene-menu-items.ts
> +    if (draft == null) return { index: -1, draft };
Don't use double equals, wrap if body in curly brackets

```suggestion
    if (!draft) {
        return { index: -1, draft };
    }
```

2024-01-03 03:08 UTC, kevboh commented on src/view/explorer/scene-menu-items.ts
> +    if (draft == null) return;
```suggestion
    if (!draft) {
        return;
    }
```

2024-01-03 03:08 UTC, kevboh commented on src/view/explorer/scene-menu-items.ts
> +    if (draft == null) return;
```suggestion
    if (!draft) {
        return;
    }
```

2024-01-03 03:08 UTC, kevboh commented on src/view/explorer/scene-menu-items.ts
> +    if (draft == null) return;
```suggestion
    if (!draft) {
        return;
    }
```

2024-01-03 03:08 UTC, kevboh commented on src/view/explorer/scene-menu-items.ts
> +    if (draft == null) return;
```suggestion
    if (!draft) {
        return;
    }
```

2024-01-19 21:23 UTC, kevboh approved these changes

2024-01-19 21:23 UTC, merged